# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:  Like a Cantor Dust...  ...  ...
email: anshul.choudhary@uni-oldenburg.de
email_md5: 59c09cbe288a38fb1525bbf76cdd23d9
description: I’m an engineer turned physicist currently working on the intersection of `chaos theory` and `machine learning`.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://anshu957.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: anshulheaven
github_username:  anshu957
scholar_username: Tybi34wAAAAJ
researchgate: Anshul_Choudhary
orcid: 0000-0001-6651-5224
name: Anshul Choudhary
google_analytics: UA-128380562-1

disqus:
    shortname: anshu957

# Build settings
markdown: kramdown
#theme: minima
jekyll_env: "production"
comments: true
higlighter: rouge

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name     : "Anshul Choudhary"

plugins:
    - jekyll-feed
    - jekyll-redirect-from
    - jekyll-font-awesome-sass
    - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


